### ISSUE TITLE
org.kde.KStyle.Adwaita 5.15-22.08

### ISSUE THREAD

**Issue by Eonfge** [flathub/org.kde.KStyle.Adwaita#11]
A new version of the Free Desktop Sdk ande KDE has been released! would it also be possible to  create a new branch for Adwaita so all the KDE Apps like more similar to my main theme?

**Comment by travier** [comment]
Thanks for the reminder. I've pushed the branch and the build is in progress: https://buildbot.flathub.org/#/apps/org.kde.KStyle.Adwaita~2F5.15-22.08

**Comment by travier** [comment]
Hold on, we're not using this runtime yet. Not sure what's happening here.

**Comment by Eonfge** [comment]
I noticed it when QBittorrent upgraded to the latest version:
https://github.com/flathub/org.qbittorrent.qBittorrent/commit/2f094d86563f1521ad2e81d1ffbfcda1015a8e55

**Comment by travier** [comment]
OK, we have "early" adopters.
