### ISSUE TITLE
KDE 5.15 is available

### ISSUE THREAD

**Issue by Eonfge** [flathub/org.kde.KStyle.Adwaita#4]
I tried to make a pull request in the past but that didn't work out the right way, so for now all just remind you about the new KDE release. Don't forget that the latest version of Adwaita QT is 1.1.4 (e5dfd0be75b31dc3b823de0c4bd320b9a6995b89)

**Comment by Eonfge** [comment]
@grulja Hey, are you available to look into this? You've also made the last updates so hopefully you can help us out here.

**Comment by Siosm** [comment]
I've created a [temporary 5.15 branch](https://github.com/flathub/org.kde.KStyle.Adwaita/tree/tmp/5.15). WDYT @flathub/kde?

**Comment by cho2** [comment]
https://github.com/flathub/org.kde.KStyle.Adwaita/tree/branch/5.15

**Comment by grulja** [comment]
Adwaita-qt and QGnomePlatform should be now available for Qt 5.15.
