### ISSUE TITLE
Dark theme no longer functional

### ISSUE THREAD

**Issue by Eonfge** [flathub/org.kde.KStyle.Adwaita#6]
Testing with both Qbittorrent and Kid3, I found that the KDE branding stopped working since about yesterday.

![Screenshot from 2021-04-14 22-10-36](https://user-images.githubusercontent.com/33983090/114772651-58fef780-9d6e-11eb-8d0e-0180818d5a1b.png)

```
Name         : flatpak
Version      : 1.10.2
Release      : 2.fc33
Architecture : x86_64
Size         : 7.4 M
Source       : flatpak-1.10.2-2.fc33.src.rpm
Repository   : @System
From repo    : updates
Summary      : Application deployment framework for desktop apps
URL          : http://flatpak.org/
License      : LGPLv2+
Description  : flatpak is a system for building, distributing and running sandboxed desktop
             : applications on Linux. See https://wiki.gnome.org/Projects/SandboxedApps for
             : more information.
```

**Comment by grulja** [comment]
This is an issue in the runtime. I opened a request to fix this: https://invent.kde.org/packaging/flatpak-kde-runtime/-/merge_requests/44

**Comment by Eonfge** [comment]
Issue has been resolved with the latest updates
